version: '3'
services:
  ftp:
    image: stilliard/pure-ftpd:hardened
    ports:
      - 21:21
      - 30000-30009:30000-30009
    volumes:
      - "./data:/home/ftp"
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      - FTP_USER_NAME=ftp
      - FTP_USER_PASS=1234
      - FTP_USER_HOME=/home/ftp
    command: "/run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R  -s -A -j -Z -H -4 -E -R -X -x -p 30000:30009 -c 5 -C 5"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - ftp
      - db
    environment:
      - FTP_SERVER=ftpqqq
      - FTP_USER=ftp
      - FTP_PASS=1234

  db:
    image: mysql-server:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql:/var/lib/mysql